spring:
  application:
    name: led
  datasource:
    url: jdbc:h2:file:./data/db
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driverClassName: org.h2.Driver
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
  mail:
    host: ${SMTP_HOST:test}
    port: ${SMTP_PORT:22}
    username: ${SMTP_USERNAME:test}
    password: ${SMTP_PASSWORD:test}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true